name: CI

on:
  [pull_request]

env:
  DOTNET_VERSION: '3.1.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup .NET v${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create Azure Function Artifact
      run: dotnet publish ./src/AzureFunctions --configuration Release
